firebase deploy --only functions
=== Deploying to 'adneon-y5bae'...

i  deploying functions
Running command:
+  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
!  functions: missing required API cloudbuild.googleapis.com. Enabling now...
!  artifactregistry: missing required API artifactregistry.googleapis.com. Enabling now...

Error: Your project adneon-y5bae must be on the Blaze (pay-as-you-go) plan to complete this command. Required API cloudbuild.googleapis.com can't be enabled until the upgrade is complete. To upgrade, visit the following URL:

https://console.firebase.google.com/project/adneon-y5bae/usage/details

C:\Users\asus\CashQueryApp\studio> see i cant have blaze plan as i dont have money can i get that api for free from somewhere or something what should i do?